version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Banco
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "3030:5432"
    restart: always
